/**
 * "VOLUMEPAD Test": a wallet-standard Solana wallet for headless CDP flows. Injected by
 * scripts/play-ui.mjs with Page.addScriptToEvaluateOnNewDocument, AFTER tweetnacl (window.nacl)
 * and `window.VOLUMEPAD_TEST_SECRET` (64-byte secret key as a number array, generated by the script —
 * never a real wallet). It signs messages and transactions for real with that key;
 * signAndSendTransaction sends to `window.VOLUMEPAD_TEST_RPC` (devnet or the fake RPC).
 * Local testing only: never ship this file to a page.
 */
(() => {
  const nacl = window.nacl;
  const secret = Uint8Array.from(window.VOLUMEPAD_TEST_SECRET || []);
  if (!nacl || secret.length !== 64) return;

  const ALPHABET = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";
  const b58 = (bytes) => {
    const digits = [0];
    for (const byte of bytes) {
      let carry = byte;
      for (let i = 0; i < digits.length; i++) {
        carry += digits[i] << 8;
        digits[i] = carry % 58;
        carry = (carry / 58) | 0;
      }
      while (carry > 0) {
        digits.push(carry % 58);
        carry = (carry / 58) | 0;
      }
    }
    let out = "";
    for (let i = 0; i < bytes.length && bytes[i] === 0; i++) out += "1";
    for (let i = digits.length - 1; i >= 0; i--) out += ALPHABET[digits[i]];
    return out;
  };
  const shortvec = (bytes, offset) => {
    let len = 0;
    let size = 0;
    for (;;) {
      const b = bytes[offset + size];
      len |= (b & 0x7f) << (size * 7);
      size++;
      if ((b & 0x80) === 0) return [len, size];
    }
  };

  const publicKey = secret.slice(32);
  const address = b58(publicKey);
  const chains = ["solana:mainnet", "solana:devnet", "solana:testnet", "solana:localnet"];
  const account = Object.freeze({
    address,
    publicKey,
    chains,
    features: ["solana:signMessage", "solana:signTransaction", "solana:signAndSendTransaction"],
    label: "VOLUMEPAD Test",
  });

  /** Signs a wire transaction (legacy or v0) in place at this key's signer slot. */
  const signTx = (wire) => {
    const tx = Uint8Array.from(wire);
    const [numSigs, sigLen] = shortvec(tx, 0);
    const messageStart = sigLen + numSigs * 64;
    const message = tx.subarray(messageStart);
    let o = message[0] & 0x80 ? 1 : 0; // v0 prefix
    const required = message[o];
    o += 3;
    const [numKeys, keyLen] = shortvec(message, o);
    o += keyLen;
    let index = -1;
    for (let k = 0; k < Math.min(numKeys, required); k++) {
      const key = message.subarray(o + k * 32, o + k * 32 + 32);
      if (key.every((v, i) => v === publicKey[i])) index = k;
    }
    if (index < 0) throw new Error("This transaction does not need the VOLUMEPAD Test signature.");
    const signature = nacl.sign.detached(message, secret);
    tx.set(signature, sigLen + index * 64);
    return { tx, signature };
  };

  const send = async (bytes) => {
    let bin = "";
    bytes.forEach((b) => (bin += String.fromCharCode(b)));
    const r = await fetch(window.VOLUMEPAD_TEST_RPC, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ jsonrpc: "2.0", id: 1, method: "sendTransaction", params: [btoa(bin), { encoding: "base64" }] }),
    });
    const j = await r.json();
    if (j.error) throw new Error(j.error.message);
    return j.result;
  };

  const listeners = { change: [] };
  let connected = false;
  const emit = () => listeners.change.forEach((fn) => fn({ accounts: connected ? [account] : [] }));
  const V = "1.0.0";

  const wallet = {
    version: V,
    name: "VOLUMEPAD Test",
    icon: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 8 8'%3E%3Crect width='8' height='8' rx='2' fill='%233d5afe'/%3E%3C/svg%3E",
    chains,
    get accounts() {
      return connected ? [account] : [];
    },
    features: {
      "standard:connect": {
        version: V,
        connect: async (input) => {
          if (input?.silent && !connected) return { accounts: [] };
          connected = true;
          emit();
          return { accounts: [account] };
        },
      },
      "standard:disconnect": {
        version: V,
        disconnect: async () => {
          connected = false;
          emit();
        },
      },
      "standard:events": {
        version: V,
        on: (event, fn) => {
          (listeners[event] ||= []).push(fn);
          return () => (listeners[event] = listeners[event].filter((f) => f !== fn));
        },
      },
      "solana:signMessage": {
        version: V,
        signMessage: async (...inputs) =>
          inputs.map(({ message }) => {
            window.__KUDOS_LAST_MESSAGE = new TextDecoder().decode(message);
            return { signedMessage: message, signature: nacl.sign.detached(message, secret) };
          }),
      },
      "solana:signTransaction": {
        version: V,
        supportedTransactionVersions: ["legacy", 0],
        signTransaction: async (...inputs) => inputs.map(({ transaction }) => ({ signedTransaction: signTx(transaction).tx })),
      },
      "solana:signAndSendTransaction": {
        version: V,
        supportedTransactionVersions: ["legacy", 0],
        signAndSendTransaction: async (...inputs) =>
          Promise.all(
            inputs.map(async ({ transaction }) => {
              const { tx, signature } = signTx(transaction);
              await send(tx);
              return { signature };
            }),
          ),
      },
    },
  };

  const callback = ({ register }) => register(wallet);
  window.addEventListener("wallet-standard:app-ready", (event) => callback(event.detail));
  window.dispatchEvent(new CustomEvent("wallet-standard:register-wallet", { detail: callback }));
  window.__VOLUMEPAD_TEST_ADDRESS = address;
})();
